project:
  type: website
  output-dir: docs

website:
  title: "Pairs Trading"
  navbar:
    left:
      - text: Home
        file: index.qmd
      - text: About
        file: about.qmd
      - text: Indicators
        file: indicators.qmd
      - text: Sample pairs
        file: sample_pairs.qmd
      - text: Interactive analysis
        file: interactive_analysis.qmd

    right:
      - icon: github
        href: https://github.com/szhang95/PairsTrading_JVS
        aria-label: GitHub

format:
  html:
    theme: cerulean
    toc: true
    math: mathjax

execute:
  enabled: true
  freeze: false