project:
  type: website
  output-dir: docs

website:
  title: "Pairs Trading"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd

    right:
      - icon: github
        href: https://github.com/JackieXi1012/PairsTrading_JVS
        aria-label: GitHub
