project:
  type: website
  output-dir: docs

website:
  title: "Pairs Trading"
  favicon: images/background.jpg
  navbar:
    background: dark
    logo: images/background.jpg
    title: "Pairs Trading"
    left:
      - text: "Home"
        icon: house
        file: index.qmd
      - text: "About"
        icon: info-circle
        file: about.qmd
      - text: "Indicators"
        icon: graph-up
        file: indicators.qmd
      - text: "Sample pairs"
        icon: bar-chart
        file: sample_pairs.qmd
      - text: "Interactive analysis"
        icon: gear-fill
        file: interactive_analysis.qmd

    right:
      - icon: github
        href: https://github.com/szhang95/PairsTrading_JVS
        aria-label: GitHub

  page-footer:
    left: "© 2025 Pairs Trading JVS. All rights reserved."
    right:
      - icon: github
        href: https://github.com/szhang95/PairsTrading_JVS

format:
  html:
    theme:
      light: [cosmo, styles.css]
      dark: [darkly, styles.css]
    toc: true
    toc-depth: 3
    toc-title: "On this page"
    toc-location: right
    toc-expand: true
    code-copy: true
    code-tools: true
    highlight-style: github
    math: mathjax
    css: styles.css
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/firacode@6.2.0/distr/fira_code.css">
        <style>
          /* Additional fix for sidebar overlapping content */
          @media (min-width: 992px) {
            .page-columns {
              display: grid;
              gap: 1.5rem;
              grid-template-columns: minmax(0, 1fr) 300px;
            }
            .toc-content {
              grid-column: 1;
            }
            #toc-title {
              padding-top: 0;
            }
            main > div.sidebar.toc-left {
              padding-right: 0.5rem;
            }
            main > div.sidebar.toc-right {
              padding-left: 0.5rem;
            }
            main {
              padding-left: 1rem;
              padding-right: 1rem;
            }
          }
        </style>

execute:
  enabled: true
  freeze: false